language: php
sudo: false
php:
    - 7.2.2
#   - 7.3.0
#   - 7.4.0
    - "nightly"
matrix:
    fast_finish: true
    allow_failures:
        - php: "nightly"
os:
    - windows
    - linux
install:
    - travis_retry composer install --no-interaction
    - wget -c -nc --retry-connrefused --tries=0 https://github.com/php-coveralls/php-coveralls/releases/download/v2.0.0/php-coveralls.phar
    - chmod +x php-coveralls.phar
    - php php-coveralls.phar --version
before_script:
    - mkdir -p build/logs
    - ls -al
script:
    - ./vendor/bin/phpunit --coverage-clover build/logs/clover.xml
after_success:
    - travis_retry php php-coveralls.phar -v
branches:
    only: master
cache:
    directories:
        - vendor
        - $HOME/.cache/composer
